;; Auto generated by `pyim-generate-dict-cache-file', don't edit it by hand!

#s(hash-table size 1000000 test equal rehash-size 1.5 rehash-threshold 0.8 data ("ce-shi" ("测试") "c-s" ("测试") "ren-cai" ("人才") "r-c" ("人才") "lao" ("老") "l" ("老") "hou" ("侯") "h" ("侯") "lao-hou" ("老侯") "l-h" ("老侯")))
